### ISSUE TITLE
Project hosting

### ISSUE THREAD

**Issue by Adarsh077** [HimanSC/Travel-Landing-Page#1]
Try to use github pages to host static sites. I would like to see them 😄 
Go to Repo Settings > Pages

**Comment by HimanSC** [comment]
It's just a basic one bro not so good😅😂

**Comment by Adarsh077** [comment]
Still, I want to see.
You were not there when I started web development. 
Ask Omkar and Yash how lame my projects were initially 😅.

**Comment by HimanSC** [comment]
https://smashedtrash.github.io/Travel-Landing-Page/

Pls don't laugh 😂😂
It's just a single page for drop down menu you can view it  from mobile😂

**Comment by Adarsh077** [comment]
This is way (almost 10x) better than what I use to make 😅
